name = "hemanth-portfolio-contact"
main = "worker-telegram.js"
compatibility_date = "2023-12-01"

[env.production]
name = "hemanth-portfolio-contact"

# Uncomment and configure if you want to use KV for rate limiting and storage
# [[env.production.kv_namespaces]]
# binding = "CONTACT_FORM_KV"
# id = "your-kv-namespace-id-here"

[vars]
# Public variables (non-sensitive)
ENVIRONMENT = "production"
